# Assignment 1 - NumPy

**Name:** Manpreet Singh
**Subgroup:** 3c25
**Roll No:** 102303357

## Q1: Questions on Basic NumPy Array

### (a) Reverse the NumPy array:
arr = np.array([1, 2, 3, 6, 4, 5])

In [1]:
import numpy as np
arrayy = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arrayy[::-1]
print("new array: ",reversed_arr)

new array:  [5 4 6 3 2 1]


### (b) Flatten the NumPy arr:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

using any two NumPy in-built methods

In [2]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat_1= array1.flatten()
print("Flattened array: ", flat_1)

flat_2= array1.ravel()
print("Raveled array: ", flat_2)

Flattened array:  [1 2 3 2 4 5 1 2 3]
Raveled array:  [1 2 3 2 4 5 1 2 3]


### (c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

equalcheck = np.array_equal(arr1, arr2)
print("arr1 and arr2 are equal: ", equalcheck)

arr1 and arr2 are equal:  True


### (d) Find the most frequent value and their indice(s) in the following arrays:
(i) x = np.array([1,2,3,4,5,1,2,1,1,1])

(ii) y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

ux, cx = np.unique(x, return_counts=True)
uy, cy = np.unique(y, return_counts=True)

freq_x = ux[np.argmax(cx)]
ix = np.where(x == freq_x)[0]

freq_y = uy[np.argmax(cy)]
iy = np.where(y == freq_y)[0]

print("Most frequent element in x:", freq_x, "at indices:", ix)
print("Most frequent element in y:", freq_y, "at indices:", iy)


Most frequent element in x: 1 at indices: [0 5 7 8 9]
Most frequent element in y: 1 at indices: [0 1 2]


### (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find:
i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [5]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

s_total = np.sum(gfg)
print("Total sum of elements in the matrix:", s_total)

s_rows = np.sum(gfg, axis=1)
print("Sum of each row:\n", s_rows)

s_cols = np.sum(gfg, axis=0)
print("Sum of each column:", s_cols)


Total sum of elements in the matrix: 45
Sum of each row:
 [[14]
 [16]
 [15]]
Sum of each column: [[20  9 16]]


### (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find:
i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [6]:
import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

d_sum = np.trace(n_array)
print("Sum of diagonal elements:", d_sum)

vals, vecs = np.linalg.eig(n_array)
print("Eigenvalues:", vals)
print("Eigenvectors:\n", vecs)

inv_mat = np.linalg.inv(n_array)
print("Inverse of the matrix:\n", inv_mat)

det = np.linalg.det(n_array)
print("Determinant of the matrix:", det)


Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


### (g) Multiply the following matrices and also find covariance between matrices using NumPy:
i.  p = [[1, 2], [2, 3]] and q = [[4, 5], [6, 7]]
    
ii. p = [[1, 2], [2, 3], [4, 5]] and q = [[4, 5, 1], [6, 7, 2]]

In [7]:
import numpy as np

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.dot(p1, q1)
cov1 = np.cov(p1.flatten(), q1.flatten())

print("Product of p1 and q1:\n", product1)
print("Covariance between p1 and q1:\n", cov1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

product2 = np.dot(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())

print("Product of p2 and q2:\n", product2)
print("Covariance between p2 and q2:\n", cov2)


Product of p1 and q1:
 [[16 19]
 [26 31]]
Covariance between p1 and q1:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Product of p2 and q2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between p2 and q2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


### (h) For the matrices x and y, find inner, outer and cartesian product:
x = np.array([[2, 3, 4], [3, 2, 9]])

y = np.array([[1, 5, 0], [5, 10, 3]])

In [8]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)
outer = np.outer(x, y)
cartesian_product = np.array(np.meshgrid(x, y)).T.reshape(-1, 2)

print("Inner product:\n", inner)
print("Outer product:\n", outer)
print("Cartesian product:\n", cartesian_product)

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


## Q2: Based on NumPy Mathematics and Statistics

### (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [9]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_array = np.abs(array)
print("Absolute value of array:\n", abs_array)

flat = array.flatten()

percentiles_flat = np.percentile(flat, [25, 50, 75])
percentiles_col = np.percentile(array, [25, 50, 75], axis=0)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)

print("25th, 50th, 75th percentile (flattened):", percentiles_flat)
print("25th, 50th, 75th percentile (columns):\n", percentiles_col)
print("25th, 50th, 75th percentile (rows):\n", percentiles_row)

mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Mean (flattened):", mean_flat)
print("Median (flattened):", median_flat)
print("Standard Deviation (flattened):", std_flat)

print("Mean (columns):", mean_col)
print("Median (columns):", median_col)
print("Standard Deviation (columns):", std_col)

print("Mean (rows):", mean_row)
print("Median (rows):", median_row)
print("Standard Deviation (rows):", std_row)


Absolute value of array:
 [[1 2 3]
 [4 5 6]]
25th, 50th, 75th percentile (flattened): [-3.5 -0.5  2.5]
25th, 50th, 75th percentile (columns):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
25th, 50th, 75th percentile (rows):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (flattened): -0.5
Median (flattened): -0.5
Standard Deviation (flattened): 3.8622100754188224
Mean (columns): [-1.5  1.5 -1.5]
Median (columns): [-1.5  1.5 -1.5]
Standard Deviation (columns): [2.5 3.5 4.5]
Mean (rows): [ 0.66666667 -1.66666667]
Median (rows): [ 1. -4.]
Standard Deviation (rows): [2.05480467 4.78423336]


### (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
Find floor, ceiling and truncated value, rounded values

In [10]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

floor_values = np.floor(a)
print("Floor values:", floor_values)

ceil_values = np.ceil(a)
print("Ceil values:", ceil_values)

truncated_values = np.trunc(a)
print("Truncated values:", truncated_values)

rounded_values = np.round(a)
print("Rounded values:", rounded_values)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceil values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


## Q3: Based on Searching and Sorting

### (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [11]:
import numpy as np

arr = np.array([10, 52, 62, 16, 16, 54, 453])

arr_sorted = np.sort(arr)
print("Sorted array:", arr_sorted)

sorted_idx = np.argsort(arr)
print("Indices of sorted array:", sorted_idx)

top_4_small = np.partition(arr, 3)[:4]
print("Smallest 4 elements:", top_4_small)

top_5_large = np.partition(arr, -5)[-5:]
print("Largest 5 elements:", top_5_large)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
Smallest 4 elements: [10 16 16 52]
Largest 5 elements: [ 16  52  54  62 453]


### (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only

ii. Float elements only

In [12]:
import numpy as np

arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

ints = arr[arr == arr.astype(int)]
print("Integer elements in the array:", ints)

floats = arr[arr != arr.astype(int)]
print("Float elements in the array:", floats)


Integer elements in the array: [1. 2. 3. 2.]
Float elements in the array: [1.2 2.2]


## Q4:

(a) Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)

In [18]:
from PIL import Image
import numpy as np
import os

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if arr.ndim == 2:
        np.savetxt("grayscale_output.txt", arr, fmt='%d')
    else:
        reshaped = arr.reshape(-1, arr.shape[-1])
        np.savetxt("rgb_output.txt", reshaped, fmt='%d')
    return arr




(b) Load the saved file into jupyter notebook.

In [19]:
arr = img_to_array("/content/imageapple.webp")

if os.path.exists("grayscale_output.txt"):
    gray_data = np.loadtxt("grayscale_output.txt", dtype=int)
    print(gray_data)

if os.path.exists("rgb_output.txt"):
    rgb_data = np.loadtxt("rgb_output.txt", dtype=int)
    print(rgb_data)

[[197 197 197]
 [197 197 197]
 [197 197 197]
 ...
 [199 166 143]
 [196 163 138]
 [187 155 130]]
